# server configuration
server:
    port: 8081
    shutdown: graceful

# spring configuration
spring:
    application:
        name: hibernate-search
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 8000
            validation-timeout: 10000
            max-lifetime: 298000
    jpa:
        properties:
            hibernate:
                format_sql: true
                search:
                    backend:
                        lucene_version: LATEST
                        directory:
                            root: ${user.home}/work/indexed-data/mysql-local
                        analysis:
                            configurer: com.hzn.search.config.CustomLuceneAnalysisConfigurer
                    indexing:
                        listeners:
                            enabled: true # 트랜잭션이 커밋될 때 자동 인덱싱
#                    configuration_property_checking:
#                        strategy: ignore
#                    index:
#                        initialize: true
        open-in-view: false
        hibernate:
            naming:
                physical-strategy: com.hzn.search.config.UpperCasePhysicalNamingStrategy

# application configuration
cors:
    allowed:
        origins: "*"
        headers: "*"
        methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
